### ISSUE TITLE
Functionality todo

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/tamRgo#1]
Unexported functions (utils):

- [x] Create blueprint
- [x] Post blueprint to gist
- [x] Delete blueprint gist
- [x] Update blueprint gist
- [x] Read blueprint gist
- [x] Write ID to environ
- [x] Status incrementer

Exported functions:

- [x] 'Lay egg' (create, post, update Renviron)
- [x] 'Load' pet (value isn't sticking in the Renviron for some reason)
- [x] Status summary
- [ ] Feed pet
- [ ] Play with pet
- [ ] Clean pet
- [x] Release pet

Add to blueprint?

- [x] Pet ID
* ~Link to gist~ (derived from the per ID, so nevermind?)
* ~Seed~ (nah, don't want to recreate a pet actually)

General

- [ ] Refactor messages

**Comment by matt-dray** [comment]
~If #4 is adopted, then also:~

* ~GitHub Action script~
* ~R script for GitHub Action~
* ~Set up new repo with YAML blueprint and GHA files~

Probably not, so nevermind.

**Comment by matt-dray** [comment]
If #7 then:

- [x] Create environ file
- [x] Write to it
- [x] Use it add `pet_id` to the user's current environment

**Comment by matt-dray** [comment]
Refactoring as per #20, so these checklists are redundant now.
